title: Minima Blog
email: minima.blog@gmail.com
description: >
  What is your aweome blog about?
  Say more
  Say more

baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: minima_blog
github_username:  minima_blog

minima:
  skin: solarized-light

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - archive.html
  - about.markdown

social:
  linkedin: minima_blog

markdown: kramdown
kramdown:
  parse_block_html: true
  parse_span_html: true
  footnote_nr: 1
  footnote_backlink: "&#8617;&#xfe0e;"
  enable_coderay: false
  auto_ids: true
  auto_id_stripping: true
